### ISSUE TITLE
Using Numpad keys to switch between desktops

### ISSUE THREAD

**Issue by Jaziny** [widavies/WinJump#33]
Hi,
I'm found this software pretty good for my usage and I appreciated, but one thing I couldn't figure out that how to do that is how to use Alt + Numpad keys to switch between desktops? Is there a way to do that?
And another thing I should mention that the color of the desktop number shown in taskbar is white that is not proper for light themes, is there a way to change the color of the desktop number?

Thank you

Kind regards
Jaziny

**Comment by widavies** [comment]
@Jaziny Thanks for letting me know about light theme not working! Apparently Microsoft changed the name of the setting in the registry in a recent update and I hadn't noticed it. 

Download this new version [here](https://github.com/widavies/WinJump/releases/tag/2.0.9). Let me know if it works and I can close this issue.

Yes, numpad is supported, you can use any keys specified [here](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=windowsdesktop-7.0) in the config file.

To change this, right click WinJump in the systray and select *Open config file*:
![image](https://github.com/widavies/WinJump/assets/11671115/dd623b6e-2e2c-47d2-a45d-aa72635cb895)

In your config file, replace `d0`, `d1`, `d2`, etc. with `NumPad0`, `NumPad1`, etc. so that you config file looks like this:

```
{
  "toggle-groups": [],
  "jump-current-goes-to-last": false,
  "change-desktops-with-scroll": true,
  "move-window-to-desktop": {
      "shortcut": "alt+shift" 
  },
  "jump-to": [
    {
      "Shortcut": "win+NumPad0",
      "desktop": 10
    },
    {
      "Shortcut": "win+NumPad1",
      "desktop": 1
    },
    {
      "Shortcut": "win+NumPad2",
      "desktop": 2
    },
    {
      "Shortcut": "win+NumPad3",
      "desktop": 3
    },
    {
      "Shortcut": "win+NumPad4",
      "desktop": 4
    },
    {
      "Shortcut": "win+NumPad5",
      "desktop": 5
    },
    {
      "Shortcut": "win+NumPad6",
      "desktop": 6
    },
    {
      "Shortcut": "win+NumPad7",
      "desktop": 7
    },
    {
      "Shortcut": "win+NumPad8",
      "desktop": 8
    },
    {
      "Shortcut": "win+NumPad9",
      "desktop": 9
    }
  ]
}
```

Note that you will need to have scroll lock on for it to work, otherwise you'll have to create additional mappings for the keys when num lock is off (let me know if you'd like me to show you how to do this).

**Comment by Jaziny** [comment]
Thank you for your fast respond, I downloaded new version and the problem solved, also now I can use numpad keys for changing desktops and it is enjoyable, very appreciated.

**Comment by widavies** [comment]
@Jaziny Great to hear! Enjoy!
